# override stages for rpm building
stages:
  - .pre
  - package

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
default:
  image: $CI_REGISTRY/pdp/ndpf/image-builder/debianbuilder:12

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GBP_BUILD_CMD: "gbp buildpackage --git-no-create-orig --git-ignore-branch --git-ignore-new --git-builder='sbuild -d $SCHROOT --build-dir=builddeb --dpkg-source-opts=\"--diff-ignore=origtargz --extend-diff-ignore=|.git\"'"
 
make_origtargz:
  stage: .pre
  tags:
    - docker
  script:
    - VERSION=`dpkg-parsechangelog -S Version`
    - NAME=`dpkg-parsechangelog -S Source`
    - git-deborig HEAD || true
    - ls -l ..
    - mkdir builddeb
    - mv ../*.orig.tar.* builddeb/
  artifacts:
    paths:
      - builddeb/
    when: on_success
    access: all
    expire_in: 30 days

.build_debian:
  stage: package
  variables:
    DISTRIBUTION: UNRELEASED
  tags:
    - docker
  script:
    - RELEASE=build1
    - MESSAGE="Automated build"
    - cp builddeb/*.orig.tar.* ..
    - if [ "$NIGHTLY_BUILD" == 1 ]; then RELEASE=~`date +%Y%m%d`.$CI_COMMIT_SHORT_SHA; MESSAGE="Nightly build" ; fi
    - if [ -n "$CI_COMMIT_TAG" ]; then RELEASE=.release.$CI_COMMIT_TAG; MESSAGE="Tagged release $CI_COMMIT_TAG"; fi
    - dch -l${RELEASE}. --distribution $DISTRIBUTION "$MESSAGE"
    - apt-get -y build-dep .
    - gbp buildpackage --git-no-create-orig --git-ignore-branch --git-ignore-new --git-builder='debuild -uc -us --source-option="--extend-diff-ignore=|.git.*"'
    - find ../ -type f -maxdepth 1 -exec cp {} builddeb/ \;
  artifacts:
    paths:
      - builddeb/
  rules:
    - if: $CI_COMMIT_SHA
    - if: $CI_COMMIT_TAG
    - if: $NIGHTLY_BUILD
  
build_debian_bookworm:
  image: $CI_REGISTRY/pdp/ndpf/image-builder/debianbuilder:12
  extends:
    - .build_debian
  variables:
    DISTRIBUTION: bookworm

build_ubuntu_yammy:
  image: $CI_REGISTRY/pdp/ndpf/image-builder/ubuntubuilder:22
  extends:
    - .build_debian
  variables:
    DISTRIBUTION: yammy

build_ubuntu_noble:
  image: $CI_REGISTRY/pdp/ndpf/image-builder/ubuntubuilder:24
  extends:
    - .build_debian
  variables:
    DISTRIBUTION: noble
